default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5

development:
 <<: *default
 database: applikey-test-task_development

test:
 <<: *default
 database: applikey-test-task_test

production:
 <<: *default
 database: applikey-test-task_production
 username: applikey-test-task
 password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>